engines:
  bundler-audit:
    enabled: false
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  eslint:
    enabled: false
  fixme:
    enabled: false
  rubocop:
    enabled: false
  brakeman:
    enabled: true
    exclude_fingerprints:
    - 0a616a63f4f81f91e6cd422960070286
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- features/**/*
- script/**/*
- spec/**/*
- vendor/**/*
- "**.scss"
